-- require('nvim-treesitter').setup {
--   -- Directory to install parsers and queries to (prepended to `runtimepath` to have priority)
--   install_dir = vim.fn.stdpath('data') .. '/site'
-- }
-- require('nvim-treesitter').install { 'c', 'lua', 'vim', 'java' }
-- 
-- vim.api.nvim_create_autocmd('FileType', {
--   pattern = { '*.hs', '*.c', '*.lua', '*.java' },
--   callback = function()
--       print('hello')
--       vim.treesitter.start()
--   end,
-- })

-- require'nvim-treesitter'.setup {
--   -- A list of parser names, or "all" (the four listed parsers should always be installed)
--   ensure_installed = { "c", "lua", "vim", "java", "haskell" },
-- 
--   -- Install parsers synchronously (only applied to `ensure_installed`)
--   sync_install = false,
-- 
--   -- Automatically install missing parsers when entering buffer
--   -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
--   auto_install = true,
-- 
--   init = function()
--       vim.api.nvim_create_autocmd('FileType', {
--           callback = function()
--               pcall(vim.treesitter.start)
--               vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
--           end,
--       })
-- 
--       local ensureInstalled = {
--         'lua', 'python', 'typescript',
--         -- ... your parsers
--       }
--       local alreadyInstalled = require('nvim-treesitter.config').get_installed()
--       local parsersToInstall = vim.iter(ensureInstalled)
--         :filter(function(parser)
--           return not vim.tbl_contains(alreadyInstalled, parser)
--         end)
--         :totable()
--       require('nvim-treesitter').install(parsersToInstall)
--   end,
-- 
--   -- init = function()
--   --   vim.api.nvim_create_autocmd('FileType', {
--   --     callback = function()
--   --       -- Enable treesitter highlighting and disable regex syntax
--   --       pcall(vim.treesitter.start)
--   --       -- Enable treesitter-based indentation
--   --       vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()" 
--   --     end,
-- 
--   incremental_selection = {
--       enable = true,
--       keymaps = {
--           init_selection = "gnn", -- set to `false` to disable one of the mappings
--           node_incremental = "grn",
--           scope_incremental = "grc",
--           node_decremental = "grm",
--       },
--   },
-- }
-- 
-- vim.api.nvim_create_autocmd('FileType', {
--     pattern = { 'rust', 'javascript', 'zig', 'haskell' },
--     callback = function()
--         -- syntax highlighting, provided by Neovim
--         vim.treesitter.start()
--         -- folds, provided by Neovim
--         vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
--         vim.wo.foldmethod = 'expr'
--         -- indentation, provided by nvim-treesitter
--         vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
--     end,
-- })
-- 
-- 
-- -- local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
-- -- parser_config.lilypond = {
-- --   install_info = {
-- --     url = "~/projects/tree-sitter-lilypond/lilypond", -- local path or git repo
-- --     files = {"src/parser.c"}, -- note that some parsers also require src/scanner.c or src/scanner.cc
-- --     -- optional entries:
-- --     branch = "main", -- default branch in case of git repo if different from master
-- --     generate_requires_npm = false, -- if stand-alone parser without npm dependencies
-- --     requires_generate_from_grammar = false, -- if folder contains pre-generated src/parser.c
-- --   },
-- --   filetype = "ly", -- if filetype does not match the parser name
-- -- }
